---
title: "Choose an AI/ML Service"
css: ../styles.css
---

Source: [Choose an Artificial Intelligence / Machine Learning Service](https://learn.microsoft.com/en-us/azure/architecture/guide/technology-choices/technology-choices-overview)

AI is the capability of a computer to imitate intelligent human behavior. Through AI, machines can analyze images, comprehend speech, interact in natural ways, and make predictions based on data. Review these articles to learn about the AI and machine learning technology choices that are available in Azure:

|Article|Summary|
|--|--|
|[Choose an Azure Cognitive Services technology.](https://learn.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/cognitive-services)|Learn about cognitive services that you can use in AI applications and data flows.|
|[Natural language processing technology.](https://learn.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/natural-language-processing)|Choose a natural language processing service for sentiment analysis, topic and language detection, key phrase extraction, and document categorization.|
|[Compare machine learning products and technologies.](https://learn.microsoft.com/en-us/azure/architecture/ai-ml/guide/data-science-and-machine-learning)|Compare options for building, deploying, and managing your machine learning models. Decide which products to use for your solution.|
|[MLflow and Azure Machine Learning.](https://learn.microsoft.com/en-us/azure/machine-learning/concept-mlflow?toc=/azure/architecture/toc.json&bc=/azure/architecture/_bread/toc.json)|Learn about how Azure Machine Learning uses MLflow to log metrics and artifacts from machine learning models and deploy your machine learning models to an endpoint.|
