---
title: "Choose a Data Store"
css: ../styles.css
---

Source: [Choose a Data Store](https://learn.microsoft.com/en-us/azure/architecture/guide/technology-choices/technology-choices-overview)

The cloud is changing the way applications are designed, including how data is processed and stored. These articles can help you choose a data solution:

|Article|Summary|
|--|--|
|[Understand data store models.](https://learn.microsoft.com/en-us/azure/architecture/guide/technology-choices/data-store-overview)|Learn about the high-level differences between the various data storage models in Azure data services.|
|[Choose an Azure data store for your application.](https://learn.microsoft.com/en-us/azure/architecture/guide/technology-choices/data-store-decision-tree)|Use a flowchart to choose an Azure data store.|
|[Criteria for choosing a data store.](https://learn.microsoft.com/en-us/azure/architecture/guide/technology-choices/data-store-considerations)|Review some general considerations for choosing a data store.|
|[Choose a big data storage technology in Azure.](https://learn.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/data-storage)|Compare big data storage options in Azure. View key selection criteria and a capability matrix.|
|[OLAP solutions.](https://learn.microsoft.com/en-us/azure/architecture/data-guide/relational-data/online-analytical-processing)|Learn about online analytical processing (OLAP) solutions for organizing large databases and supporting complex analysis without affecting transactional systems.|
|[OLTP solutions.](https://learn.microsoft.com/en-us/azure/architecture/data-guide/relational-data/online-transaction-processing)|Learn about atomicity, consistency, and other features of online transaction processing (OLTP), which manages transactional data and supports querying.|
|[Data warehousing.](https://learn.microsoft.com/en-us/azure/architecture/data-guide/relational-data/data-warehousing)|Learn about data warehousing in Azure. A data warehouse is a repository of integrated data from disparate sources that's used for reporting and analysis of the data.|
|[Data lakes.](https://learn.microsoft.com/en-us/azure/architecture/data-guide/scenarios/data-lake)|Learn about data lake storage repositories, which can hold terabytes or petabytes of data in a native, raw format.|
|[Non-relational data and NoSQL.](https://learn.microsoft.com/en-us/azure/architecture/data-guide/big-data/non-relational-data)|Learn about non-relational databases that store data as key/value pairs, graphs, time series, objects, and other storage models.|
|[Choose a data pipeline orchestration technology.](https://learn.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/pipeline-orchestration-data-movement)|Choose an Azure data pipeline orchestration technology to automate pipeline orchestration, control flow, and data movement workflows.|
|[Choose a search data store.](https://learn.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/search-options)|Learn about the capabilities of search data stores in Azure and the key criteria for choosing one that best matches your needs.|
|[Transfer data to and from Azure.](https://learn.microsoft.com/en-us/azure/architecture/data-guide/scenarios/data-transfer)|Learn about Azure data transfer options like Azure Import/Export, Azure Data Box, Azure Data Factory, and command-line and graphical interface tools.|
